(()=>{'use strict';
const P=window.NYXIA_PORTAL||{},$=id=>document.getElementById(id);let token=sessionStorage.getItem('nyxia_token')||'';
function navs(){return Array.from(document.querySelectorAll('[data-page-key]'))}
function setActive(key){navs().forEach(n=>n.classList.toggle('active',n.dataset.pageKey===key));const dd=$('atelier-group');if(dd)dd.classList.toggle('has-active',!!dd.querySelector('[data-page-key="'+CSS.escape(key)+'"]'))}
function closeMobile(){const a=$('sidebar'),b=$('mobile-menu-backdrop');a?.classList.remove('mobile-open');b?.classList.remove('mobile-open')}
function openPage(key){const page=P.pages&&P.pages[key];if(!page)return;const frame=$('portal-frame');$('empty-state').style.display='none';frame.classList.add('active');setActive(key);const sep=page.includes('?')?'&':'?';frame.src=page+sep+'t='+encodeURIComponent(token);sessionStorage.setItem('nyxia_portal_last_page',key);closeMobile()}
function toggleAtelier(){const g=$('atelier-group');if(!g)return;g.classList.toggle('open');$('atelier-toggle')?.setAttribute('aria-expanded',g.classList.contains('open')?'true':'false')}
async function logout(){try{await fetch('/api/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})})}catch(_){}sessionStorage.removeItem('nyxia_token');location.replace('/login.html')}
async function auth(){if(!token){location.replace('/login.html');return false}try{const r=await fetch('/api/check-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(!d.valid){sessionStorage.removeItem('nyxia_token');location.replace('/login.html');return false}const name=d.firstname||localStorage.getItem('nyxia_username')||'';$('user-name').textContent=name||'Membre';$('header-username').textContent=name||'';$('user-avatar').textContent=(name||'N').charAt(0).toUpperCase();return true}catch(_){return true}}
document.addEventListener('DOMContentLoaded',async()=>{if(!(await auth()))return;navs().forEach(n=>n.addEventListener('click',()=>openPage(n.dataset.pageKey)));$('atelier-toggle')?.addEventListener('click',toggleAtelier);$('logout-btn')?.addEventListener('click',logout);$('mobile-menu-btn')?.addEventListener('click',()=>{$('sidebar')?.classList.toggle('mobile-open');$('mobile-menu-backdrop')?.classList.toggle('mobile-open')});$('mobile-menu-backdrop')?.addEventListener('click',closeMobile);const last=sessionStorage.getItem('nyxia_portal_last_page');const first=(last&&P.pages&&P.pages[last])?last:P.defaultPage;if(first&&P.pages&&P.pages[first])openPage(first)})
})();
